# -*- coding: utf-8 -*-
"""project3_Multi_Constellation_GNSS:_One_Satellite_per_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBLrk7dqecC5d8x45xj9oOTAH-sHEyi0

=============================================================================
🛰️ Project 3 — Multi-Constellation GNSS: One Satellite per System
=============================================================================
 Author   : Hakim El Azzouzi
 Degree   : MSc Global Navigation Satellite Systems
            Mohammed First University, Oujda, Morocco
 Email    : elazzouzihakim10@gmail.com
 LinkedIn : https://linkedin.com/in/Hakim-El-Azzouzi
 Location : Luxembourg 🇱🇺
-----------------------------------------------------------------------------
 Station  : AUCK00NZL  —  Auckland, New Zealand  (GeoNet / LINZ Network)
 File     : AUCK00NZL_R_20260010000_01D_30S_MO.rnx
 Receiver : TRIMBLE ALLOY
 Antenna  : TRM115000.00
 Format   : RINEX 3.05  |  Mixed Constellations  |  30-second sampling
 Date     : 2026-01-01  (Day-of-Year 001)
-----------------------------------------------------------------------------
 Description
 -----------
Modern GNSS receivers track **five satellite constellations simultaneously**.
This project picks **one representative satellite from each system** and compares them side by side:

## 📡 Why Do Pseudoranges Differ Between Systems?

Each constellation uses a different orbital altitude, so the **geometric distance**
(and therefore the pseudorange magnitude) differs:

```
GPS      ~20,200–25,000 km range
GLONASS  ~19,100–24,000 km range   (lower orbit → smaller range)
Galileo  ~23,222–28,000 km range   (higher orbit → larger range)
BeiDou   varies (MEO like GPS, or GEO at 36,000 km → very flat arc)
QZSS     ~36,000 km quasi-GEO      (stays almost fixed in the sky over Japan/Pacific)
-----------------------------------------------------------------------------
 **About the projects**
 ----------------------
# Step1: Install & Import Libraries
# Step2: Load the RINEX File
# Step3: Identifying One Representative Satellite per Constellation
# Step4: Plot 1: Multi-Constellation Pseudorange Arcs
# Step5: Plot 2: Multi-Constellation SNR Heatmap
# Step6: Plot 3: Satellite Availability Timeline (All Constellations)
# Step7: Numerical Summary per Constellation
=============================================================================
"""

pip install --upgrade georinex

# ──────────────────────────────────────────────────────────
# Step 1 — Install & Import Libraries
# ──────────────────────────────────────────────────────────
# Install georinex if not already installed
# Uncomment the line below if you are running this for the first time:
# !pip install --upgrade georinex

import georinex as gr
import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.colors import LinearSegmentedColormap
import warnings

warnings.filterwarnings('ignore')  # suppress xarray FutureWarnings during load

# Global plot style (dark GNSS theme)
plt.rcParams.update({
    'figure.dpi': 120,
})

print('✅ All libraries loaded successfully')
print(f'   georinex version : {gr.__version__}')
print(f'   xarray version   : {xr.__version__}')

# ─────────────────────────────────────────────────────────────────
# Step 2 — Load the RINEX File
# ─────────────────────────────────────────────────────────────────
# RINEX FILE PATH HERE
obs_path = "/AUCK00NZL_R_20260010000_01D_30S_MO.rnx"  # ← change this path
# Read the file header first (fast — no data loaded yet)
print("📋 FILE HEADER")
print("=" * 60)
header = gr.rinexheader(obs_path)

for key, value in header.items():
    print(f"{key:<25}: {value}")

print()

# Load all observation data (interval=30 means keep 30-sec rate)

print("⏳ Loading observation data (this may take 1–2 minutes)...")
obs = gr.load(obs_path, interval=30)
print()
print("✅ Data loaded!")
print(obs)

# ─────────────────────────────────────────────────────────────────
# Step 3 — Identifying One Representative Satellite per Constellation
# ─────────────────────────────────────────────────────────────────
# Constellation configuration
# Each system uses different observable codes depending on the receiver
CONST_CONFIG = {
    'G': {'name': 'GPS',     'color': '#2196F3', 'pr_codes': ['C1C', 'C2W'], 'snr_codes': ['S1C', 'S2W']},
    'R': {'name': 'GLONASS', 'color': '#F44336', 'pr_codes': ['C1C', 'C1P'], 'snr_codes': ['S1C', 'S1P']},
    'E': {'name': 'Galileo', 'color': '#4CAF50', 'pr_codes': ['C1X', 'C5X'], 'snr_codes': ['S1X', 'S5X']},
    'C': {'name': 'BeiDou',  'color': '#FF9800', 'pr_codes': ['C1X', 'C2I'], 'snr_codes': ['S1X', 'S2I']},
    'J': {'name': 'QZSS',   'color': '#9C27B0', 'pr_codes': ['C1C', 'C1X'], 'snr_codes': ['S1C', 'S1X']},
}

# Group all satellites by constellation
all_sv = obs.sv.values
constellations = {}
for prefix in ['G', 'R', 'E', 'C', 'J']:
    sats = sorted([s for s in all_sv if s.startswith(prefix)])
    if sats:
        constellations[prefix] = sats

# For each constellation: pick the satellite with most valid epochs
# and find its best pseudorange and SNR observable code
selected = {}   # will hold: prefix → {sat, pr_code, snr_code, pr_data, snr_data}

print("🛰️  Selecting best satellite per constellation:")
print()
print(f"{'System':<12} {'Satellite':<10} {'PR Code':<8} {'SNR Code':<9} {'Valid Epochs':>12} {'Mean SNR':>10}")
print("-" * 65)

for prefix, sats in constellations.items():
    cfg = CONST_CONFIG[prefix]
    best_sat = None
    best_pr_code = None
    best_snr_code = None
    best_count = 0
    best_pr = None
    best_snr = None

    for sat in sats:
        # Try each pseudorange code
        for pr_code in cfg['pr_codes']:
            if pr_code not in obs.data_vars:
                continue
            pr = obs[pr_code].sel(sv=sat).to_series().dropna()
            if len(pr) > best_count:
                # Also find SNR
                snr = None
                snr_code_used = None
                for snr_code in cfg['snr_codes']:
                    if snr_code in obs.data_vars:
                        s = obs[snr_code].sel(sv=sat).to_series().dropna()
                        if len(s) > 0:
                            snr = s
                            snr_code_used = snr_code
                            break
                best_count = len(pr)
                best_sat = sat
                best_pr_code = pr_code
                best_snr_code = snr_code_used
                best_pr = pr
                best_snr = snr
            break  # use first working code

    if best_sat:
        selected[prefix] = {
            'sat': best_sat,
            'pr_code': best_pr_code,
            'snr_code': best_snr_code,
            'pr': best_pr,
            'snr': best_snr,
            'color': cfg['color'],
            'name': cfg['name'],
        }
        mean_snr = best_snr.mean() if best_snr is not None else float('nan')
        snr_str = f"{mean_snr:.1f} dB-Hz" if not np.isnan(mean_snr) else "N/A"
        print(f"  {cfg['name']:<10} {best_sat:<10} {best_pr_code:<8} {str(best_snr_code):<9} {best_count:>12} {snr_str:>12}")
    else:
        print(f"  {cfg['name']:<10} — no valid data found")

print()
print(f"✅ {len(selected)} constellations selected")

# ──────────────────────────────────────────────────────
# Step 4 — Plot 1: Multi-Constellation Pseudorange Arcs
# ──────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(16, 7), facecolor="#0d1117")
ax.set_facecolor("#111827")

ax.set_title(
    'Multi-Constellation Pseudorange — One Satellite per System\n'
    'AUCK00NZL | Auckland, New Zealand | 2026-01-01',
    fontsize=13, fontweight='bold', color="#ffffff"
)

for prefix, info in selected.items():
    pr = info['pr']
    if pr is None or len(pr) == 0:
        continue

    ax.plot(
        pr.index,
        pr.values / 1e6,   # convert metres → million metres
        color=info['color'],
        lw=2.0,
        alpha=0.9,
        label=f"{info['name']} {info['sat']}  [{info['pr_code']}]"
    )

    # Annotate the closest approach for each satellite
    if len(pr) > 10:
        idx_min = pr.idxmin()
        ax.scatter(idx_min, pr[idx_min] / 1e6, color=info['color'], s=50, zorder=5)

ax.set_ylabel('Pseudorange [Mm = million metres]', fontsize=11, color="#aaaaaa")
ax.set_xlabel('UTC Time (HH:MM)', fontsize=11, color="#aaaaaa")

ax.tick_params(colors="#aaaaaa")
ax.grid(True, color="#222222", linewidth=0.5)

for spine in ax.spines.values():
    spine.set_edgecolor("#333333")

ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
ax.xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")

legend = ax.legend(
    fontsize=10, loc='upper right',
    framealpha=0.3, facecolor="#1a1a2e", edgecolor="#444444"
)
for text in legend.get_texts():
    text.set_color("white")

plt.tight_layout()
plt.savefig('plot1_multi_constellation_pseudorange.png', dpi=150,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

print('✅ Plot saved: plot1_multi_constellation_pseudorange.png')
print()
print('💡 Interpretation:')
print('   • Each arc = satellite rising, passing overhead, then setting')
print('   • Higher orbital altitude  → larger pseudorange (e.g. Galileo > GPS)')
print('   • Lower orbital altitude   → smaller pseudorange (e.g. GLONASS < GPS)')
print('   • A nearly flat arc        → satellite is near-geostationary (QZSS / BeiDou GEO)')
print('   • Dots mark the closest approach (satellite highest in sky)')

# ──────────────────────────────────────────────────────────────
# Step 5 — Plot 2: Multi-Constellation SNR Heatmap
# ──────────────────────────────────────────────────────────────
# Build SNR arrays (full time axis including NaN gaps)
time_index = pd.to_datetime(obs.time.values)
n_epochs = len(time_index)

# Ordered list of constellations for the Y axis
ordered = ['G', 'R', 'E', 'C', 'J']
rows_data = []      # SNR values for each row
row_labels = []     # Y-axis label for each row
row_colors_list = [] # colour for each label

for prefix in ordered:
    if prefix not in selected:
        continue
    info = selected[prefix]
    sat = info['sat']
    snr_code = info['snr_code']

    if snr_code is None:
        # No SNR — fill with NaN
        snr_arr = np.full(n_epochs, np.nan)
    else:
        # Get full time series (keep NaN where satellite not visible)
        snr_full = obs[snr_code].sel(sv=sat).to_series()
        snr_arr = snr_full.reindex(time_index).values

    rows_data.append(snr_arr)
    row_labels.append(f"{info['name']}\n{sat}")
    row_colors_list.append(info['color'])

n_rows = len(rows_data)

# Replace NaN with sentinel below vmin so gaps appear as dark background
snr_matrix = np.array(rows_data)
snr_display = np.where(np.isnan(snr_matrix), 5, snr_matrix)

# Custom GNSS colormap
gnss_cmap = LinearSegmentedColormap.from_list(
    "gnss_snr",
    [
        "#0d1117",  # background / no data
        "#1a0533",  # deep purple (very weak)
        "#2c3e8c",  # blue (low)
        "#0099cc",  # cyan (moderate)
        "#00e676",  # green (good)
        "#ffeb3b",  # yellow (strong)
        "#ff6f00",  # orange (excellent)
    ],
    N=256
)

# Figure
fig, ax = plt.subplots(figsize=(16, 5), facecolor="#0d1117")
ax.set_facecolor("#0d1117")

# Use imshow — handles any number of rows correctly, including 1-row case
# extent maps pixel coordinates to data coordinates (time on X, row index on Y)
ax.imshow(
    snr_display,
    aspect='auto',
    cmap=gnss_cmap,
    vmin=15, vmax=55,
    extent=[
        mdates.date2num(time_index[0]),
        mdates.date2num(time_index[-1]),
        -0.5,
        n_rows - 0.5
    ],
    origin='upper'   # row 0 at top (first constellation)
)

# Tell matplotlib the X axis contains date numbers
ax.xaxis_date()

# Colorbar using ScalarMappable (required when using imshow)
sm = plt.cm.ScalarMappable(cmap=gnss_cmap, norm=plt.Normalize(vmin=15, vmax=55))
sm.set_array([])
cbar = plt.colorbar(sm, ax=ax, pad=0.01)
cbar.set_label('SNR [dB-Hz]', color="#e0e0e0", fontsize=11)
cbar.ax.yaxis.set_tick_params(color="#aaaaaa")
plt.setp(cbar.ax.get_yticklabels(), color="#aaaaaa")

# Y axis — constellation labels with colour coding
ax.set_yticks(range(n_rows))
ax.set_yticklabels(row_labels, fontsize=10, fontweight='bold')
for tick_label, color in zip(ax.get_yticklabels(), row_colors_list):
    tick_label.set_color(color)

ax.set_title(
    'Multi-Constellation SNR Heatmap — One Satellite per System\n'
    'AUCK00NZL | Auckland, New Zealand | 2026-01-01\n'
    'Green/Yellow = strong signal  |  Blue/Purple = weak  |  Black = not visible',
    fontsize=12, fontweight='bold', color="#ffffff"
)
ax.set_xlabel('UTC Time (HH:MM)', fontsize=11, color="#e0e0e0")

ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
ax.xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")

# Horizontal separators between constellations
for y in np.arange(0.5, n_rows, 1):
    ax.axhline(y, color="#333333", lw=0.8)

for spine in ax.spines.values():
    spine.set_edgecolor("#333333")

plt.tight_layout()
plt.savefig('plot2_multi_constellation_snr_heatmap.png', dpi=150,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

print('✅ Plot saved: plot2_multi_constellation_snr_heatmap.png')
print()
print('💡 Interpretation:')
print('   • Each ROW = one constellation (GPS, GLONASS, Galileo, BeiDou, QZSS)')
print('   • Black = satellite not visible from Auckland at that time')
print('   • Green/Yellow = strong signal — good tracking conditions')
print('   • Compare rows to see which system gives the best signal in your region')

# ─────────────────────────────────────────────────────────────────────
# Step 6 — Plot 3: Satellite Availability Timeline (All Constellations)
# ─────────────────────────────────────────────────────────────────────
# Count visible satellites per constellation per epoch
# We use pseudorange presence as the visibility indicator

# Best pseudorange code per constellation
PR_CODE = {'G': 'C1C', 'R': 'C1C', 'E': 'C1X', 'C': 'C1X', 'J': 'C1C'}

def count_visible(prefix):
    """Count non-NaN epochs per time step for a given constellation."""
    sats = [s for s in obs.sv.values if s.startswith(prefix)]
    if not sats:
        return pd.Series(0, index=pd.to_datetime(obs.time.values))
    code = PR_CODE.get(prefix, 'C1C')
    # Try fallback codes if primary is not available
    for c in [code, 'C1X', 'C1C', 'C2I']:
        if c in obs.data_vars:
            return obs[c].sel(sv=sats).count(dim='sv').to_series()
    return pd.Series(0, index=pd.to_datetime(obs.time.values))

avail = {
    'G': count_visible('G'),
    'R': count_visible('R'),
    'E': count_visible('E'),
    'C': count_visible('C'),
    'J': count_visible('J'),
}

total_per_epoch = sum(avail.values())

# Figure: 2 panels
# Top   = stacked bars by constellation
# Bottom = total satellite count
fig, axes = plt.subplots(2, 1, figsize=(16, 8), sharex=True, facecolor="#0d1117")

fig.suptitle(
    'Multi-Constellation Satellite Availability — AUCK00NZL | 2026-01-01\n'
    'How many satellites from each system are tracked per epoch',
    fontsize=13, fontweight='bold', color="#ffffff"
)

for ax in axes:
    ax.set_facecolor("#111827")
    ax.tick_params(colors="#aaaaaa")
    ax.grid(True, color="#222222", linewidth=0.5)
    for spine in ax.spines.values():
        spine.set_edgecolor("#333333")

# Panel 1 — Stacked bars
CONST_NAMES = {'G': 'GPS', 'R': 'GLONASS', 'E': 'Galileo', 'C': 'BeiDou', 'J': 'QZSS'}
CONST_COLORS_MAP = {
    'G': '#2196F3',
    'R': '#F44336',
    'E': '#4CAF50',
    'C': '#FF9800',
    'J': '#9C27B0',
}

t = avail['G'].index
bottom = np.zeros(len(t))

for prefix in ['G', 'R', 'E', 'C', 'J']:
    vals = avail[prefix].values.astype(float)
    axes[0].bar(
        t, vals,
        bottom=bottom,
        color=CONST_COLORS_MAP[prefix],
        alpha=0.85,
        width=pd.Timedelta('30s'),
        label=CONST_NAMES[prefix],
        edgecolor='none'
    )
    bottom += vals

axes[0].axhline(4, color="#F44336", ls='--', lw=1.2, alpha=0.7,
                label='Min for standalone GPS positioning (4 sats)')

axes[0].set_ylabel('Satellites Tracked', color="#aaaaaa", fontsize=11)
axes[0].set_title(
    'Satellites per epoch — stacked by constellation',
    fontsize=10, color="#ffffff"
)

legend = axes[0].legend(
    ncol=6, fontsize=9, loc='upper right',
    framealpha=0.3, facecolor="#1a1a2e", edgecolor="#444444"
)
for text in legend.get_texts():
    text.set_color("white")

# Panel 2 — Total satellite count
axes[1].plot(t, total_per_epoch.values, color="#ffffff", lw=1.5,
             label='Total all constellations')
axes[1].fill_between(t, total_per_epoch.values, color="#ffffff", alpha=0.08)

axes[1].axhline(4,  color="#F44336", ls='--', lw=1.2, alpha=0.7, label='Min GPS-only (4)')
axes[1].axhline(total_per_epoch.mean(), color="#FFEB3B", ls='--', lw=1.2,
                label=f'Daily mean ({total_per_epoch.mean():.0f} sats)')

axes[1].set_ylabel('Total Satellites', color="#aaaaaa", fontsize=11)
axes[1].set_xlabel('UTC Time (HH:MM)', color="#aaaaaa", fontsize=11)
axes[1].set_title(
    'Total multi-GNSS satellite count — why multi-constellation matters',
    fontsize=10, color="#ffffff"
)

legend2 = axes[1].legend(
    fontsize=9, framealpha=0.3, facecolor="#1a1a2e", edgecolor="#444444"
)
for text in legend2.get_texts():
    text.set_color("white")

axes[1].xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
axes[1].xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.savefig('plot3_constellation_availability.png', dpi=150,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

print('✅ Plot saved: plot3_constellation_availability.png')
print()
print('💡 Interpretation:')
print(f'   • GPS alone: ~{avail["G"].mean():.0f} sats average  →  good, but limited in challenging environments')
print(f'   • All systems: ~{total_per_epoch.mean():.0f} sats average  →  much stronger geometry and reliability')
print('   • More satellites = better DOP (Dilution of Precision) = more accurate position')
print('   • Multi-GNSS is why modern phones and professional receivers are so accurate')

# ─────────────────────────────────────────────
# Step 7 — Numerical Summary per Constellation
# ─────────────────────────────────────────────
# Print a clean comparison table
print("📊 MULTI-CONSTELLATION SUMMARY")
print("=" * 80)
print(f"{'System':<10} {'Satellite':<10} {'PR [Mm] min–max':<22} {'SNR mean':>10} {'Visible %':>10}")
print("-" * 80)

total_epochs = len(obs.time)

for prefix in ['G', 'R', 'E', 'C', 'J']:
    if prefix not in selected:
        print(f"  {CONST_NAMES[prefix]:<8}  — not in file")
        continue

    info = selected[prefix]
    pr = info['pr']
    snr = info['snr']

    if pr is None or len(pr) == 0:
        print(f"  {info['name']:<8}  — no pseudorange data")
        continue

    pr_range = f"{pr.min()/1e6:.2f} – {pr.max()/1e6:.2f} Mm"
    snr_mean = f"{snr.mean():.1f} dB-Hz" if snr is not None and len(snr) > 0 else "N/A"
    visible_pct = f"{len(pr) / total_epochs * 100:.1f}%"

    print(f"  {info['name']:<8}  {info['sat']:<10} {pr_range:<22} {snr_mean:>12} {visible_pct:>10}")

print()
print("Total multi-GNSS satellites in file :", len(obs.sv.values))
print(f"Average total sats tracked per epoch : {total_per_epoch.mean():.1f}")
print(f"Peak sats tracked (best epoch)       : {int(total_per_epoch.max())}")

